### ISSUE TITLE
instructions to create mongodb

### ISSUE THREAD

**Issue by TomasKulhanek** [TomasKulhanek/B2NOTE-VirtualMachine#1]
`./manage.py runserver` seems not to detect and create empty database.

```
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/vagrant/b2note/b2note_devel/settings.py", line 24, in <module>
    MONGO_DATABASE_NAME = os.environ['MONGODB_NAME']
  File "/home/vagrant/b2note/venv/lib64/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'MONGODB_NAME'
```
Could you please add instructions howto and what to create in mongodb and what is expected to be se in MONGODB_NAME

**Comment by TomasKulhanek** [comment]
Some instructions left at https://docs.google.com/document/d/1bPPUkvnVjGCSo82cG1ghXD2c03wVAFC_e8q3KhAR-ls
However, following to install sqlite and mongodb leads to another issue:
```
(venv) [vagrant@localhost b2note]$ ./manage.py runserver
Unhandled exception in thread started by <function wrapper at 0x7f01d6bb8de8>
Traceback (most recent call last):
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/core/management/commands/runserver.py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 251, in raise_last_exception
    six.reraise(*_exception)
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/utils/autoreload.py", line 228, in wrapper
    fn(*args, **kwargs)
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/vagrant/b2note/venv/lib/python2.7/site-packages/django/apps/config.py", line 94, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named django_mongodb_engine
```

Obviously django_mongodb_engine is installed, but this needs to be installed into venv - not as sudo
thus at page 9. install all modules using `pip install ...` instead of `sudo pip install ...` which installs into root environment not the `venv`. After that
```
(venv) [vagrant@localhost b2note]$ ./manage.py runserver
Validating models...

0 errors found
March 20, 2019 - 15:57:22
Django version 1.5.11, using settings 'b2note_devel.settings'
Development server is running at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
```
